/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itsupportproject;

import java.awt.Component;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import javax.swing.table.AbstractTableModel;
import itsupportproject.Program;
import javax.swing.table.DefaultTableModel;
import itsupportproject.DatabaseManager;

public class DesktopGUI extends javax.swing.JFrame {

    String totalTidString;

    public DesktopGUI() throws ClassNotFoundException, SQLException {
     
        initComponents();
        //??????????????????????????????????????Populera personalklassen istället för tabellen? sen populera tabellen därifrån???
        tableTilldela.setModel(DatabaseManager.getPersDb()); //Populera tilldelatabellen
        tableTilldela.changeSelection(0,0,false, false); 
        //gör så att tabellen inte går att editera
        tableTilldela.setDefaultEditor(Object.class, null);
        tableTilldela.setRowSelectionAllowed(true);
        //??????????????? VARFÖR ÄR DESSA MED 2 GGR?
        tableTillagda.setDefaultEditor(Object.class, null);
        tableTillagda.setRowSelectionAllowed(true);
        
        
        tableVisaArenden.setModel(DatabaseManager.getAssignmentsDb());
        tableVisaArenden.setDefaultEditor(Object.class, null);
        tableVisaArenden.setRowSelectionAllowed(true);
        tableVisaArenden.setDefaultEditor(Object.class, null);
        tableVisaArenden.setRowSelectionAllowed(true);
        tableVisaArenden.changeSelection(0, 0, false, false);
        
        //Ärendebeskrivning i Visa ärende-fliken
        int tempID = 1;
        txtArendebeskrivning.setText(Program.getArendeBeskrivning(tempID));
        //Gör arbetsuppgifter otillgängliga tills man skapat ärende
        for (Component cp : panelArendeuppg.getComponents()){
            cp.setEnabled(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpPrio = new javax.swing.ButtonGroup();
        btnGrpArenden = new javax.swing.ButtonGroup();
        jTabbedPane = new javax.swing.JTabbedPane();
        tabPanelSkapa = new javax.swing.JPanel();
        panelSkapa = new javax.swing.JPanel();
        labelPrio = new javax.swing.JLabel();
        btnPrio1 = new javax.swing.JRadioButton();
        btnPrio2 = new javax.swing.JRadioButton();
        txtBudgetTid = new javax.swing.JTextField();
        labelBudgTid = new javax.swing.JLabel();
        btnPrio4 = new javax.swing.JRadioButton();
        btnPrio5 = new javax.swing.JRadioButton();
        btnPrio3 = new javax.swing.JRadioButton();
        labelArendebeskr = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArendeBeskr = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnSkapaArende = new javax.swing.JButton();
        labelSkapaArende = new javax.swing.JLabel();
        panelTillagda = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableTillagda = new javax.swing.JTable();
        labelTillagda = new javax.swing.JLabel();
        btnRegArende = new javax.swing.JButton();
        panelArendeuppg = new javax.swing.JPanel();
        labelArbUppg = new javax.swing.JLabel();
        comboArbuppg = new javax.swing.JComboBox<>();
        labelKomp = new javax.swing.JLabel();
        txtKompetens = new javax.swing.JTextField();
        labelStatus = new javax.swing.JLabel();
        labelBudgTidUppg = new javax.swing.JLabel();
        labelUppgBesk = new javax.swing.JLabel();
        labelTilldel = new javax.swing.JLabel();
        txtBudgTidArbUppg = new javax.swing.JTextField();
        comboStatus = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaUppgBesk = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableTilldela = new javax.swing.JTable();
        btnArbuppg = new javax.swing.JButton();
        labelArendeuppg = new javax.swing.JLabel();
        tabPanelVisa = new javax.swing.JPanel();
        panelVisaArende = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableVisaArenden = new javax.swing.JTable();
        btnOppnaArenden = new javax.swing.JRadioButton();
        btnAllaArenden = new javax.swing.JRadioButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtArendebeskrivning = new javax.swing.JTextArea();
        lblArendelista = new javax.swing.JLabel();
        txtBudgeteradTidArende = new javax.swing.JTextField();
        lblBudgeteradTidArende = new javax.swing.JLabel();
        lblAnvandTidArende = new javax.swing.JLabel();
        txtAnvandTidArende = new javax.swing.JTextField();
        lblArendebeskrivning = new javax.swing.JLabel();
        panelVisaUppgift = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblVisaArbetsuppgifter = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtKommentar = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtUppgiftsbeskrivning = new javax.swing.JTextArea();
        lblAnvandTidUppgift = new javax.swing.JLabel();
        txtAnvandTidUppgift = new javax.swing.JTextField();
        btnUppdateraUppgift = new javax.swing.JButton();
        btnLaggTillUppgift = new javax.swing.JButton();
        btnTaBortUppgift = new javax.swing.JButton();
        lblBeskrivningArbetsuppgift = new javax.swing.JLabel();
        lblKommentar = new javax.swing.JLabel();
        lblBudgeteradTidUppgift = new javax.swing.JLabel();
        txtBudgeteradTidUppgift = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelSkapa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, java.awt.Color.darkGray));
        panelSkapa.setToolTipText("");
        panelSkapa.setName("Skapa ärende"); // NOI18N

        labelPrio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelPrio.setText("Prioritet");

        btnGrpPrio.add(btnPrio1);
        btnPrio1.setText("1");
        btnPrio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrio1ActionPerformed(evt);
            }
        });

        btnGrpPrio.add(btnPrio2);
        btnPrio2.setText("2");

        txtBudgetTid.setEditable(false);
        txtBudgetTid.setText("0");
        txtBudgetTid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBudgetTidActionPerformed(evt);
            }
        });

        labelBudgTid.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelBudgTid.setText("Budgeterad tid (h)");

        btnGrpPrio.add(btnPrio4);
        btnPrio4.setText("4");

        btnGrpPrio.add(btnPrio5);
        btnPrio5.setText("5");

        btnGrpPrio.add(btnPrio3);
        btnPrio3.setText("3");

        labelArendebeskr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelArendebeskr.setText("Ärendebeskrivning");

        txtArendeBeskr.setColumns(20);
        txtArendeBeskr.setRows(5);
        jScrollPane1.setViewportView(txtArendeBeskr);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel1.setText("Beräknad utifrån arbetsuppgifterna");

        btnSkapaArende.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSkapaArende.setText("Skapa ärende");
        btnSkapaArende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkapaArendeActionPerformed(evt);
            }
        });

        labelSkapaArende.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSkapaArende.setText("Skapa ärende");

        javax.swing.GroupLayout panelSkapaLayout = new javax.swing.GroupLayout(panelSkapa);
        panelSkapa.setLayout(panelSkapaLayout);
        panelSkapaLayout.setHorizontalGroup(
            panelSkapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSkapaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSkapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSkapaArende)
                    .addGroup(panelSkapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelSkapaLayout.createSequentialGroup()
                            .addGroup(panelSkapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelPrio)
                                .addComponent(labelBudgTid))
                            .addGap(39, 39, 39)
                            .addGroup(panelSkapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelSkapaLayout.createSequentialGroup()
                                    .addComponent(txtBudgetTid, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel1))
                                .addGroup(panelSkapaLayout.createSequentialGroup()
                                    .addComponent(btnPrio1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnPrio2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnPrio3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnPrio4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnPrio5))
                                .addGroup(panelSkapaLayout.createSequentialGroup()
                                    .addGap(146, 146, 146)
                                    .addComponent(labelSkapaArende, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(panelSkapaLayout.createSequentialGroup()
                            .addComponent(labelArendebeskr)
                            .addGap(36, 36, 36)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        panelSkapaLayout.setVerticalGroup(
            panelSkapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSkapaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSkapaArende)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSkapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrio)
                    .addComponent(btnPrio1)
                    .addComponent(btnPrio2)
                    .addComponent(btnPrio3)
                    .addComponent(btnPrio4)
                    .addComponent(btnPrio5))
                .addGap(18, 18, 18)
                .addGroup(panelSkapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBudgTid)
                    .addComponent(txtBudgetTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(panelSkapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelArendebeskr)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSkapaArende)
                .addGap(10, 10, 10))
        );

        panelTillagda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, java.awt.Color.darkGray));

        tableTillagda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Arbetsuppgift", "Kompetenskrav", "Status", "Budg. tid", "Beskrivning", "Tilldelad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableTillagda);
        tableTillagda.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        labelTillagda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTillagda.setText("Tillagda ärendeuppgifter");

        javax.swing.GroupLayout panelTillagdaLayout = new javax.swing.GroupLayout(panelTillagda);
        panelTillagda.setLayout(panelTillagdaLayout);
        panelTillagdaLayout.setHorizontalGroup(
            panelTillagdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTillagdaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(panelTillagdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTillagdaLayout.createSequentialGroup()
                    .addGap(559, 559, 559)
                    .addComponent(labelTillagda)
                    .addContainerGap(560, Short.MAX_VALUE)))
        );
        panelTillagdaLayout.setVerticalGroup(
            panelTillagdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTillagdaLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelTillagdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTillagdaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labelTillagda)
                    .addContainerGap(194, Short.MAX_VALUE)))
        );

        btnRegArende.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegArende.setText("Registrera ärende");
        btnRegArende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegArendeActionPerformed(evt);
            }
        });

        panelArendeuppg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, java.awt.Color.darkGray));
        panelArendeuppg.setPreferredSize(new java.awt.Dimension(527, 440));

        labelArbUppg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelArbUppg.setText("Arbetsuppgift");

        comboArbuppg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Installation mjukvara", "Klientinstallation OS", "Systemtest", "Support mjukvara", "Support nätverk", "Felsökning", "Domänresurser", "Övrigt" }));
        comboArbuppg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboArbuppgActionPerformed(evt);
            }
        });

        labelKomp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelKomp.setText("Kompetenskrav");

        txtKompetens.setEditable(false);
        txtKompetens.setText("Mjukvara");
        txtKompetens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKompetensActionPerformed(evt);
            }
        });

        labelStatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelStatus.setText("Status");

        labelBudgTidUppg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelBudgTidUppg.setText("Budgeterad tid (h)");

        labelUppgBesk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelUppgBesk.setText("Uppgiftsbeskrivning");

        labelTilldel.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        labelTilldel.setText("Tilldela personal");

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrerad", "Påbörjad", "Avslutad" }));

        txtAreaUppgBesk.setColumns(20);
        txtAreaUppgBesk.setRows(5);
        jScrollPane2.setViewportView(txtAreaUppgBesk);

        tableTilldela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableTilldela.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(tableTilldela);
        tableTilldela.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnArbuppg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnArbuppg.setText("Lägg till arbetsuppgift");
        btnArbuppg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArbuppgActionPerformed(evt);
            }
        });

        labelArendeuppg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelArendeuppg.setText("Lägg till arbetsuppgift");

        javax.swing.GroupLayout panelArendeuppgLayout = new javax.swing.GroupLayout(panelArendeuppg);
        panelArendeuppg.setLayout(panelArendeuppgLayout);
        panelArendeuppgLayout.setHorizontalGroup(
            panelArendeuppgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArendeuppgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelArendeuppgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelArendeuppgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnArbuppg)
                        .addGroup(panelArendeuppgLayout.createSequentialGroup()
                            .addGroup(panelArendeuppgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelArendeuppgLayout.createSequentialGroup()
                                    .addComponent(labelTilldel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(50, 50, 50))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelArendeuppgLayout.createSequentialGroup()
                                    .addComponent(labelUppgBesk)
                                    .addGap(18, 18, 18))
                                .addGroup(panelArendeuppgLayout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(labelBudgTidUppg)
                                    .addGap(27, 27, 27)))
                            .addGroup(panelArendeuppgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtBudgTidArbUppg, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelArendeuppgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)))))
                    .addGroup(panelArendeuppgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelArendeuppgLayout.createSequentialGroup()
                            .addComponent(labelStatus)
                            .addGap(97, 97, 97)
                            .addComponent(comboStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(panelArendeuppgLayout.createSequentialGroup()
                            .addComponent(labelKomp)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtKompetens, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelArendeuppgLayout.createSequentialGroup()
                            .addComponent(labelArbUppg)
                            .addGap(56, 56, 56)
                            .addComponent(comboArbuppg, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelArendeuppgLayout.createSequentialGroup()
                .addContainerGap(264, Short.MAX_VALUE)
                .addComponent(labelArendeuppg)
                .addGap(220, 220, 220))
        );
        panelArendeuppgLayout.setVerticalGroup(
            panelArendeuppgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArendeuppgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelArendeuppg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelArendeuppgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboArbuppg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelArbUppg))
                .addGap(4, 4, 4)
                .addGroup(panelArendeuppgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKompetens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKomp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelArendeuppgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelArendeuppgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBudgTidUppg)
                    .addComponent(txtBudgTidArbUppg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelArendeuppgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelArendeuppgLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelArendeuppgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTilldel)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnArbuppg))
                    .addComponent(labelUppgBesk))
                .addContainerGap())
        );

        javax.swing.GroupLayout tabPanelSkapaLayout = new javax.swing.GroupLayout(tabPanelSkapa);
        tabPanelSkapa.setLayout(tabPanelSkapaLayout);
        tabPanelSkapaLayout.setHorizontalGroup(
            tabPanelSkapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPanelSkapaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabPanelSkapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegArende, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabPanelSkapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(panelTillagda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabPanelSkapaLayout.createSequentialGroup()
                            .addComponent(panelSkapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(panelArendeuppg, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabPanelSkapaLayout.setVerticalGroup(
            tabPanelSkapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabPanelSkapaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabPanelSkapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelArendeuppg, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                    .addComponent(panelSkapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTillagda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegArende, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        jTabbedPane.addTab("Skapa ärende", tabPanelSkapa);

        panelVisaArende.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tableVisaArenden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableVisaArenden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableVisaArendenMousePressed(evt);
            }
        });
        jScrollPane5.setViewportView(tableVisaArenden);

        btnGrpArenden.add(btnOppnaArenden);
        btnOppnaArenden.setText("Öppna ärenden");
        btnOppnaArenden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOppnaArendenActionPerformed(evt);
            }
        });

        btnGrpArenden.add(btnAllaArenden);
        btnAllaArenden.setText("Alla ärenden");
        btnAllaArenden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllaArendenActionPerformed(evt);
            }
        });

        txtArendebeskrivning.setColumns(20);
        txtArendebeskrivning.setRows(5);
        jScrollPane7.setViewportView(txtArendebeskrivning);

        lblArendelista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblArendelista.setText("Ärendelista");

        txtBudgeteradTidArende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBudgeteradTidArendeActionPerformed(evt);
            }
        });

        lblBudgeteradTidArende.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblBudgeteradTidArende.setText("Budgeterad tid (h)");

        lblAnvandTidArende.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblAnvandTidArende.setText("Använd tid (h)");

        txtAnvandTidArende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnvandTidArendeActionPerformed(evt);
            }
        });

        lblArendebeskrivning.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblArendebeskrivning.setText("Ärendebeskrivning");

        javax.swing.GroupLayout panelVisaArendeLayout = new javax.swing.GroupLayout(panelVisaArende);
        panelVisaArende.setLayout(panelVisaArendeLayout);
        panelVisaArendeLayout.setHorizontalGroup(
            panelVisaArendeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVisaArendeLayout.createSequentialGroup()
                .addGroup(panelVisaArendeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVisaArendeLayout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(lblArendelista))
                    .addGroup(panelVisaArendeLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panelVisaArendeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBudgeteradTidArende)
                            .addComponent(lblAnvandTidArende))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelVisaArendeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAnvandTidArende, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBudgeteradTidArende, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelVisaArendeLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelVisaArendeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane7)
                            .addGroup(panelVisaArendeLayout.createSequentialGroup()
                                .addComponent(btnOppnaArenden)
                                .addGap(18, 18, 18)
                                .addComponent(btnAllaArenden))
                            .addComponent(jScrollPane5)
                            .addComponent(lblArendebeskrivning))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        panelVisaArendeLayout.setVerticalGroup(
            panelVisaArendeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVisaArendeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblArendelista)
                .addGap(20, 20, 20)
                .addGroup(panelVisaArendeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOppnaArenden, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAllaArenden))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lblArendebeskrivning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelVisaArendeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBudgeteradTidArende, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBudgeteradTidArende))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVisaArendeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnvandTidArende, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnvandTidArende))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        panelVisaUppgift.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tblVisaArbetsuppgifter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblVisaArbetsuppgifter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblVisaArbetsuppgifterMousePressed(evt);
            }
        });
        jScrollPane6.setViewportView(tblVisaArbetsuppgifter);

        txtKommentar.setColumns(20);
        txtKommentar.setRows(5);
        jScrollPane8.setViewportView(txtKommentar);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Arbetsuppgifter");

        txtUppgiftsbeskrivning.setColumns(20);
        txtUppgiftsbeskrivning.setRows(5);
        jScrollPane9.setViewportView(txtUppgiftsbeskrivning);

        lblAnvandTidUppgift.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblAnvandTidUppgift.setText("Använd tid (h)");

        txtAnvandTidUppgift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnvandTidUppgiftActionPerformed(evt);
            }
        });

        btnUppdateraUppgift.setText("Uppdatera uppgift");
        btnUppdateraUppgift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUppdateraUppgiftActionPerformed(evt);
            }
        });

        btnLaggTillUppgift.setText("Lägg till ny uppgift");
        btnLaggTillUppgift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillUppgiftActionPerformed(evt);
            }
        });

        btnTaBortUppgift.setBackground(new java.awt.Color(255, 102, 102));
        btnTaBortUppgift.setText("Ta bort uppgift");

        lblBeskrivningArbetsuppgift.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblBeskrivningArbetsuppgift.setText("Beskrivning av arbetsuppgift");

        lblKommentar.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblKommentar.setText("Kommentar om uppgift");

        lblBudgeteradTidUppgift.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblBudgeteradTidUppgift.setText("Budgeterad tid (h)");

        txtBudgeteradTidUppgift.setEditable(false);
        txtBudgeteradTidUppgift.setBackground(new java.awt.Color(204, 204, 204));
        txtBudgeteradTidUppgift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBudgeteradTidUppgiftActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVisaUppgiftLayout = new javax.swing.GroupLayout(panelVisaUppgift);
        panelVisaUppgift.setLayout(panelVisaUppgiftLayout);
        panelVisaUppgiftLayout.setHorizontalGroup(
            panelVisaUppgiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVisaUppgiftLayout.createSequentialGroup()
                .addGroup(panelVisaUppgiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelVisaUppgiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelVisaUppgiftLayout.createSequentialGroup()
                            .addGap(294, 294, 294)
                            .addComponent(jLabel3))
                        .addGroup(panelVisaUppgiftLayout.createSequentialGroup()
                            .addGap(79, 79, 79)
                            .addGroup(panelVisaUppgiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblBeskrivningArbetsuppgift, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblKommentar)
                                .addComponent(jScrollPane9)
                                .addComponent(jScrollPane8)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))))
                    .addGroup(panelVisaUppgiftLayout.createSequentialGroup()
                        .addGroup(panelVisaUppgiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelVisaUppgiftLayout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(btnTaBortUppgift, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLaggTillUppgift))
                            .addGroup(panelVisaUppgiftLayout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addGroup(panelVisaUppgiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelVisaUppgiftLayout.createSequentialGroup()
                                        .addComponent(lblBudgeteradTidUppgift)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtBudgeteradTidUppgift, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelVisaUppgiftLayout.createSequentialGroup()
                                        .addComponent(lblAnvandTidUppgift)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtAnvandTidUppgift, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnUppdateraUppgift, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        panelVisaUppgiftLayout.setVerticalGroup(
            panelVisaUppgiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVisaUppgiftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblBeskrivningArbetsuppgift)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKommentar)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelVisaUppgiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBudgeteradTidUppgift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBudgeteradTidUppgift))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVisaUppgiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnvandTidUppgift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnvandTidUppgift))
                .addGap(18, 18, 18)
                .addGroup(panelVisaUppgiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUppdateraUppgift)
                    .addComponent(btnLaggTillUppgift)
                    .addComponent(btnTaBortUppgift))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabPanelVisaLayout = new javax.swing.GroupLayout(tabPanelVisa);
        tabPanelVisa.setLayout(tabPanelVisaLayout);
        tabPanelVisaLayout.setHorizontalGroup(
            tabPanelVisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPanelVisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelVisaArende, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelVisaUppgift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tabPanelVisaLayout.setVerticalGroup(
            tabPanelVisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPanelVisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabPanelVisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelVisaArende, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelVisaUppgift, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Visa ärende", tabPanelVisa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1319, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArbuppgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArbuppgActionPerformed

        // hämta arbetsuppgiftsinformation
        String valdUppgTyp = comboArbuppg.getSelectedItem().toString();
        String valdKomp = txtKompetens.getText();
        String valdStatus = comboStatus.getSelectedItem().toString();
        //Läs in uppgTid, gör om komma till punkt, ta bort felaktiga tecken
        double uppgTid = Double.parseDouble(txtBudgTidArbUppg.getText().replace(",", ".").replaceAll("[^0-9.]", ""));
        String beskrivning = txtAreaUppgBesk.getText();
        int tilldelatPersID;
        if(tableTilldela.getSelectedRow() > -1){
            tilldelatPersID = (int) tableTilldela.getValueAt(tableTilldela.getSelectedRow(), 0);
        }
        else{
            tilldelatPersID = 0;
        }

        //Anropa metod i program och lägg till uppgift i specifika ärendet
        Program.laggTillUppgift(valdUppgTyp, valdKomp, valdStatus, uppgTid, beskrivning, tilldelatPersID);
        //rensa alla fält
        comboArbuppg.setSelectedIndex(0);
        comboStatus.setSelectedIndex(0);
        txtBudgTidArbUppg.setText(null);
        txtAreaUppgBesk.setText(null);
        //uppdatera tabellen för tillagda ärenden

        DefaultTableModel tblModel = new DefaultTableModel();
        tableTillagda.setModel(tblModel);
        //tableTillagda.setShowGrid(true);
        tblModel.addColumn("Arbetsuppgift");
        tblModel.addColumn("Kompetenskrav");
        tblModel.addColumn("Status");
        tblModel.addColumn("Budg. tid");
        tblModel.addColumn("Beskrivning");
        tblModel.addColumn("Tilldelad");

        
        //Borde kunna ta bort den här och använda variablerna tidigare och lägg till rad för rad istället för att hämta hela listan varje gång
        for(int i = 0; i < Program.getUppg().size();i++){
            String typ = Program.getUppg().get(i).getUppgiftstyp();
            String komp = Program.getUppg().get(i).getKompetensKrav();
            String stat = Program.getUppg().get(i).getStatus();
            double bTid = Program.getUppg().get(i).getBudgeteradTid();
            String beskr = Program.getUppg().get(i).getBeskrivning();
            int tilld = Program.getUppg().get(i).getTilldeladPers();
            String tilldeladNamn;
            tilldeladNamn = Program.getPersNamn(tilld);    
            Object[] data = {typ, komp, stat, bTid, beskr, tilldeladNamn};
            tblModel.addRow(data);

        }

        //uppdatera totalbudgettid
        Program.setArendeTid();
        txtBudgetTid.setText(totalTidString.valueOf(Program.getLastArendeTid()));
    }//GEN-LAST:event_btnArbuppgActionPerformed
    
    
    private void txtKompetensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKompetensActionPerformed
        // TO add your handling code here:
    }//GEN-LAST:event_txtKompetensActionPerformed

    private void comboArbuppgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboArbuppgActionPerformed

        if(comboArbuppg.getSelectedItem().toString() == "Installation mjukvara"){
            txtKompetens.setText("Mjukvara");
        }
        else if(comboArbuppg.getSelectedItem().toString() == "Klientinstallation OS"){
            txtKompetens.setText("Mjukvara");
        }
        else if(comboArbuppg.getSelectedItem().toString() == "Systemtest"){
            txtKompetens.setText("Övrigt");
        }
        else if(comboArbuppg.getSelectedItem().toString() == "Klientinstallation OS"){
            txtKompetens.setText("Mjukvara");
        }
        else if(comboArbuppg.getSelectedItem().toString() == "Support mjukvara"){
            txtKompetens.setText("Mjukvara");
        }
        else if(comboArbuppg.getSelectedItem().toString() == "Support nätverk"){
            txtKompetens.setText("Nätverk");
        }
        else if(comboArbuppg.getSelectedItem().toString() == "Felsökning"){
            txtKompetens.setText("Övrigt");
        }
        else{
            txtKompetens.setText("Övrigt");
        }
    }//GEN-LAST:event_comboArbuppgActionPerformed

    private void btnSkapaArendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaArendeActionPerformed
        // Hämta ärendeinformation
        // Defaultvärde för prio = 3
        int finalPrio = 3;
        String arendeBeskr = txtArendeBeskr.getText();
        float finalBudgTid = Float.parseFloat(txtBudgetTid.getText());
        
        //kollar prioval
        if(btnPrio1.isSelected()){
            finalPrio=1;
        }
        else if(btnPrio2.isSelected()){
            finalPrio=2;
        }
        else if(btnPrio3.isSelected()){
            finalPrio=3;
        }
        else if(btnPrio4.isSelected()){
            finalPrio=4;
        }
        else if(btnPrio5.isSelected()){
            finalPrio=5;
        }

        // Skapa ärende och skicka med ärendeinformation
        // int p, String b, float bt, float ta, status
        Program.skapaArende(finalPrio,arendeBeskr,finalBudgTid,"Pågående");

        // När ärendet skapats tillgängliggörs arbetsuppgiftsfönstret
        for (Component comp : panelArendeuppg.getComponents()){
            comp.setEnabled(true);
        }
    }//GEN-LAST:event_btnSkapaArendeActionPerformed

    private void txtBudgetTidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBudgetTidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBudgetTidActionPerformed

    private void btnOppnaArendenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOppnaArendenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOppnaArendenActionPerformed

    private void btnAllaArendenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllaArendenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAllaArendenActionPerformed

    private void txtBudgeteradTidArendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBudgeteradTidArendeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBudgeteradTidArendeActionPerformed

    private void txtAnvandTidArendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnvandTidArendeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnvandTidArendeActionPerformed

    private void txtAnvandTidUppgiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnvandTidUppgiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnvandTidUppgiftActionPerformed

    private void btnUppdateraUppgiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUppdateraUppgiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUppdateraUppgiftActionPerformed

    private void btnLaggTillUppgiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillUppgiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLaggTillUppgiftActionPerformed

    private void btnPrio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrio1ActionPerformed

    private void txtBudgeteradTidUppgiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBudgeteradTidUppgiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBudgeteradTidUppgiftActionPerformed

    private void btnRegArendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegArendeActionPerformed
        //Spara ärendet till databasen
        
    }//GEN-LAST:event_btnRegArendeActionPerformed

    private void tableVisaArendenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableVisaArendenMousePressed
        int tempID = (int) tableVisaArenden.getValueAt(tableVisaArenden.getSelectedRow(),0);
        txtArendebeskrivning.setText(Program.getArendeBeskrivning(tempID));
        txtBudgeteradTidArende.setText(String.valueOf(Program.getArendeTid(tempID)));
        txtAnvandTidArende.setText(String.valueOf(Program.getArendeAnvandTid(tempID)));
        //tblVisaArbetsuppgifter
        
    }//GEN-LAST:event_tableVisaArendenMousePressed

    private void tblVisaArbetsuppgifterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVisaArbetsuppgifterMousePressed
        // Gör samma som mousepressed på visaarenden
        
        int tempID = (int) tblVisaArbetsuppgifter.getValueAt(tblVisaArbetsuppgifter.getSelectedRow(), 0);
        //txtUppgiftsbeskrivning.setText();
        //txtKommentar.setText();
        //txtBudgeteradTidUppgift.setText();
        //txtAnvandTidUppgift.setText();        
        
    }//GEN-LAST:event_tblVisaArbetsuppgifterMousePressed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesktopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesktopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesktopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesktopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DesktopGUI().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DesktopGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(DesktopGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAllaArenden;
    private javax.swing.JButton btnArbuppg;
    private javax.swing.ButtonGroup btnGrpArenden;
    private javax.swing.ButtonGroup btnGrpPrio;
    private javax.swing.JButton btnLaggTillUppgift;
    private javax.swing.JRadioButton btnOppnaArenden;
    private javax.swing.JRadioButton btnPrio1;
    private javax.swing.JRadioButton btnPrio2;
    private javax.swing.JRadioButton btnPrio3;
    private javax.swing.JRadioButton btnPrio4;
    private javax.swing.JRadioButton btnPrio5;
    private javax.swing.JButton btnRegArende;
    private javax.swing.JButton btnSkapaArende;
    private javax.swing.JButton btnTaBortUppgift;
    private javax.swing.JButton btnUppdateraUppgift;
    private javax.swing.JComboBox<String> comboArbuppg;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JLabel labelArbUppg;
    private javax.swing.JLabel labelArendebeskr;
    private javax.swing.JLabel labelArendeuppg;
    private javax.swing.JLabel labelBudgTid;
    private javax.swing.JLabel labelBudgTidUppg;
    private javax.swing.JLabel labelKomp;
    private javax.swing.JLabel labelPrio;
    private javax.swing.JLabel labelSkapaArende;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelTillagda;
    private javax.swing.JLabel labelTilldel;
    private javax.swing.JLabel labelUppgBesk;
    private javax.swing.JLabel lblAnvandTidArende;
    private javax.swing.JLabel lblAnvandTidUppgift;
    private javax.swing.JLabel lblArendebeskrivning;
    private javax.swing.JLabel lblArendelista;
    private javax.swing.JLabel lblBeskrivningArbetsuppgift;
    private javax.swing.JLabel lblBudgeteradTidArende;
    private javax.swing.JLabel lblBudgeteradTidUppgift;
    private javax.swing.JLabel lblKommentar;
    private javax.swing.JPanel panelArendeuppg;
    private javax.swing.JPanel panelSkapa;
    private javax.swing.JPanel panelTillagda;
    private javax.swing.JPanel panelVisaArende;
    private javax.swing.JPanel panelVisaUppgift;
    private javax.swing.JPanel tabPanelSkapa;
    private javax.swing.JPanel tabPanelVisa;
    private javax.swing.JTable tableTillagda;
    private javax.swing.JTable tableTilldela;
    private javax.swing.JTable tableVisaArenden;
    private javax.swing.JTable tblVisaArbetsuppgifter;
    private javax.swing.JTextField txtAnvandTidArende;
    private javax.swing.JTextField txtAnvandTidUppgift;
    private javax.swing.JTextArea txtAreaUppgBesk;
    private javax.swing.JTextArea txtArendeBeskr;
    private javax.swing.JTextArea txtArendebeskrivning;
    private javax.swing.JTextField txtBudgTidArbUppg;
    private javax.swing.JTextField txtBudgetTid;
    private javax.swing.JTextField txtBudgeteradTidArende;
    private javax.swing.JTextField txtBudgeteradTidUppgift;
    private javax.swing.JTextArea txtKommentar;
    private javax.swing.JTextField txtKompetens;
    private javax.swing.JTextArea txtUppgiftsbeskrivning;
    // End of variables declaration//GEN-END:variables
}


